In [2]:
import numpy as np


In [3]:
arr= np.array([1,3,4,9,7])

In [4]:
arr

array([1, 3, 4, 9, 7])

In [ ]:
type(arr)

numpy.ndarray

**2d array**

In [5]:
arr2= np.array([[1,3],[4,7]])

In [6]:
arr2

array([[1, 3],
       [4, 7]])

**3-D** array
No. of [] brackets =3


In [ ]:
arr3= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**to check dimension**

In [ ]:
arr3.ndim

3

In [ ]:
arr3.shape

(2, 2, 3)

In [ ]:
 np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [ ]:
np.linspace(1,9,5)

array([1., 3., 5., 7., 9.])

**Difference between shallow copy and deep copy**

In [7]:
arr2

array([[1, 3],
       [4, 7]])

In [8]:
shallowArr= arr2

In [9]:

deepArr= np.copy(arr2)

In [10]:
arr2[0][0]=5

In [11]:
arr2

array([[5, 3],
       [4, 7]])

In [12]:
shallowArr

array([[5, 3],
       [4, 7]])

In [13]:
deepArr

array([[1, 3],
       [4, 7]])

**from function in Numpy**

In [14]:
np.fromfunction(lambda i,j: i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [15]:
np.fromfunction(lambda i,j: i+j, (4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [16]:
np.fromfunction(lambda i,j: i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

**To create identity matrix**

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Reshape function in Numpy**

In [21]:
dataset= np.linspace(2,9,50)

In [22]:
dataset

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
       3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
       4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
       4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143,
       5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
       6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
       7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
       7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
       8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ])

In [25]:
dataset.shape

(50,)

In [24]:
dataset.reshape(2,1,25)

array([[[2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
         2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
         3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
         4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
         4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143]],

       [[5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
         6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
         7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
         7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
         8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ]]])